### ISSUE TITLE
RCTRootView.h' file not found

### ISSUE THREAD

**Issue by sonicviz** [MantarayAR/emotions-quiz-react-native#1]
Hi,
Tried running the project via the instructions but get "RCTRootView.h' file not found" in XCode?

**Comment by idmontie** [comment]
I believe this is because I was using an experimental animation feature in React Native.

I'm not sure if they have changed React Native no longer require this step, but you will need to follow ~~the solution found [here in this Stackoverflow answer](http://stackoverflow.com/questions/30675628/react-native-rtcrootview-h-not-found).~~

Thanks for bringing this to my attention. I will document it in the README.md.

EDIT:

The final comment on this issue has the steps required: https://github.com/brentvatne/react-native-svg/issues/11

**Comment by idmontie** [comment]
Update: I updated the README to have some additional steps on getting the RCTRootView dependency resolved.

**Comment by sonicviz** [comment]
ty!

**Comment by sonicviz** [comment]
Hi,

I still can’t figure out what 

Import file under "Build Phase" into the "Link Binary with Library". Click the plus under "Link Binary with Library", and hit "Add Other...". Then navigate to the directory node_modules -> react-native -> React -> Base -> RCTRootView.m

Actually means?

What does Import file under "Build Phase" into the "Link Binary with Library” mean?

There is no “Build phase” I can see. There is no relation to menu items in XCode.

**Comment by rheupler** [comment]
Sonic are you still stuck? Click on your project on the right panel when you open XCode. Then in the middle you'll see a navbar with one option being Build Phase. When you see that, you can follow the rest of the steps.

**Comment by sonicviz** [comment]
Still can't navigate to it though as node is installed to /usr/local/lib/node_modules and I have no access in the file dialog that shows up in xcode. Tried some terminal commands like "defaults write com.apple.finder AppleShowAllFiles TRUE" but not showing.

Is there some other magic apple trick you need to do to actually get admin access to your own file system? I can easily browse  /usr/local/lib/node_modules with forklift but not finder.

**Comment by chicobean** [comment]
I still get this error from XCode:

warning: skipping file '/Users/Usama/Downloads/react-native-video-0.8.0-beta/node_modules/react-native/React/Views/RCTView.m' (unexpected file type 'sourcecode.c.objc' in Frameworks & Libraries build phase)

Please help if there is a simple workaround to this.

**Comment by mgfjx** [comment]
Hi, @chicobean @sonicviz , if the above methods have not solved your problem, then you can try my method: `Build Settings` -> `Header Search Path`, open it , your `RN` path may be like this `$ (SRCROOT) / react-native / React`, if your `Node_modules` is under the project root directory, then you have to modify `$ (SRCROOT) / node_modules / react-native / React`, hope it works.
